CREATE TABLE IF NOT EXISTS dwh.dim_commodities (
    commodity_id text PRIMARY KEY,
    commodity_name text,
    group_type text,
    group_actual boolean,
    group_active boolean,
    commodity_code_system text,
    commodity_code text,
    commodity_code_display text,
    commodity_code_text text,
    unit_system text,
    unit_code text,
    unit_display text,
    unit_text text,
    official_identifier text,
    secondary_identifier text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_commodity_stock_movements (
    observation_id text PRIMARY KEY,
    effective_datetime timestamptz,
    issued_datetime timestamptz,
    observation_status text,
    commodity_id text,
    commodity_name text,
    commodity_default_unit text,
    location_id text,
    encounter_id text,
    performer_practitioner_id text,
    event_system text,
    event_code text,
    event_label text,
    commodity_category_system text,
    commodity_category_code text,
    commodity_category_display text,
    movement_system text,
    movement_code text,
    movement_display text,
    movement_type text,
    event_quantity numeric,
    event_quantity_unit text,
    event_quantity_code text,
    event_quantity_system text,
    running_balance numeric,
    running_balance_unit text,
    running_balance_code text,
    running_balance_system text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.dim_current_commodity_stock (
    commodity_id text PRIMARY KEY,
    commodity_name text,
    commodity_default_unit text,
    observation_id text,
    effective_datetime timestamptz,
    event_code text,
    event_label text,
    movement_type text,
    running_balance numeric,
    running_balance_unit text,
    location_id text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_commodity_stockout_periods (
    flag_id text PRIMARY KEY,
    commodity_id text,
    commodity_name text,
    commodity_default_unit text,
    flag_status text,
    is_current_stockout boolean,
    stockout_started_at timestamptz,
    stockout_ended_at timestamptz,
    stockout_duration interval,
    flag_system text,
    flag_code text,
    flag_display text,
    flag_text text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.ref_cebs_signal_types (
    signal_code text PRIMARY KEY,
    signal_label text,
    include_in_reporting boolean DEFAULT true,
    updated_at timestamptz DEFAULT now()
);

INSERT INTO dwh.ref_cebs_signal_types (signal_code, signal_label, include_in_reporting)
VALUES
    ('no-signal','No Signal Reported',true),
    ('fever-with-bleeding-or-yellow-or-red-eyes','Any person with fever and signs of bleeding, red or yellow eyes',true),
    ('unexplained-rash-with-fever-and-weakness','Any person with unexplained rash plus fever and body weakness',true),
    ('animal-sudden-death-or-strange-behavior','Any sudden or unexplained death or strange behaviour in animals',true),
    ('dog-or-wild-animal-bite','Any person bitten by a dog or wild animal',true),
    ('abnormal-change-in-water','Any abnormal change in drinking water color, smell, or taste',true),
    ('abrupt-climate-event','Any abrupt climate-related event like heatwaves, floods, or droughts',true),
    ('other-public-health-threat','Any other public health threat',true)
ON CONFLICT (signal_code)
DO UPDATE SET signal_label = EXCLUDED.signal_label, include_in_reporting = EXCLUDED.include_in_reporting, updated_at = now();

CREATE TABLE IF NOT EXISTS dwh.fact_cebs_observation_components (
    observation_id text,
    component_index integer,
    effective_datetime timestamptz,
    issued_datetime timestamptz,
    observation_status text,
    location_id text,
    encounter_id text,
    performer_practitioner_id text,
    signal_system text,
    signal_code text,
    signal_label text,
    signal_description text,
    cebs_category_system text,
    cebs_category_code text,
    cebs_category_display text,
    component_system text,
    component_code text,
    component_display text,
    component_text text,
    component_label text,
    value_string text,
    value_boolean boolean,
    value_quantity numeric,
    value_quantity_unit text,
    value_quantity_code text,
    value_quantity_system text,
    value_datetime timestamptz,
    value_codeable_concept_code text,
    value_codeable_concept_system text,
    value_codeable_concept_display text,
    value_codeable_concept_text text,
    component_value_text text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now(),
    PRIMARY KEY (observation_id, component_index)
);

CREATE TABLE IF NOT EXISTS dwh.fact_cebs_observations (
    observation_id text PRIMARY KEY,
    effective_datetime timestamptz,
    issued_datetime timestamptz,
    observation_status text,
    cebs_status_label text,
    has_signal boolean,
    location_id text,
    encounter_id text,
    performer_practitioner_id text,
    signal_system text,
    signal_code text,
    signal_label text,
    reviewed_signal_label text,
    signal_description text,
    cebs_category_system text,
    cebs_category_code text,
    cebs_category_display text,
    vht_name text,
    vht_phone text,
    vht_village text,
    reporter_practitioner_id text,
    latitude numeric,
    longitude numeric,
    verification_method text,
    supervisor_signal_description text,
    vht_signal_description text,
    chew_people_ill numeric,
    chew_people_dead numeric,
    chew_animals_involved text,
    chew_animals_affected numeric,
    chew_animals_dead numeric,
    threat_start_time text,
    threat_start_datetime timestamptz,
    facility_informed_date text,
    facility_informed_datetime timestamptz,
    animal_health_referral text,
    additional_information text,
    chew_verification_timestamp text,
    chew_verification_datetime timestamptz,
    chew_name text,
    chew_phone text,
    verifier_practitioner_id text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fact_commodity_movements_commodity ON dwh.fact_commodity_stock_movements(commodity_id);
CREATE INDEX IF NOT EXISTS idx_fact_commodity_movements_effective ON dwh.fact_commodity_stock_movements(effective_datetime);
CREATE INDEX IF NOT EXISTS idx_fact_commodity_movements_type ON dwh.fact_commodity_stock_movements(movement_type);
CREATE INDEX IF NOT EXISTS idx_current_commodity_stock_location ON dwh.dim_current_commodity_stock(location_tag_id);
CREATE INDEX IF NOT EXISTS idx_stockout_periods_commodity ON dwh.fact_commodity_stockout_periods(commodity_id);
CREATE INDEX IF NOT EXISTS idx_stockout_periods_current ON dwh.fact_commodity_stockout_periods(is_current_stockout);
CREATE INDEX IF NOT EXISTS idx_cebs_components_observation ON dwh.fact_cebs_observation_components(observation_id);
CREATE INDEX IF NOT EXISTS idx_cebs_components_code ON dwh.fact_cebs_observation_components(component_system, component_code);
CREATE INDEX IF NOT EXISTS idx_cebs_observations_effective ON dwh.fact_cebs_observations(effective_datetime);
CREATE INDEX IF NOT EXISTS idx_cebs_observations_signal ON dwh.fact_cebs_observations(signal_code);
CREATE INDEX IF NOT EXISTS idx_cebs_observations_status ON dwh.fact_cebs_observations(cebs_status_label);
