CREATE TABLE IF NOT EXISTS dwh.fact_encounters (
    encounter_id text PRIMARY KEY,
    patient_id text,
    practitioner_id text,
    organization_id text,
    location_id text,
    encounter_status text,
    class_code text,
    class_system text,
    class_display text,
    type_code text,
    type_system text,
    type_display text,
    type_text text,
    service_type_code text,
    service_type_system text,
    service_type_display text,
    service_type_text text,
    reason_code text,
    reason_system text,
    reason_display text,
    reason_text text,
    period_start timestamptz,
    period_end timestamptz,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_conditions (
    condition_id text PRIMARY KEY,
    patient_id text,
    encounter_id text,
    condition_code text,
    condition_system text,
    condition_display text,
    condition_text text,
    clinical_status_code text,
    clinical_status_system text,
    clinical_status_display text,
    verification_status_code text,
    verification_status_system text,
    verification_status_display text,
    category_code text,
    category_system text,
    category_display text,
    category_text text,
    severity_code text,
    severity_system text,
    severity_display text,
    severity_text text,
    recorded_date timestamptz,
    onset_datetime timestamptz,
    abatement_datetime timestamptz,
    condition_start_date date,
    condition_end_date date,
    is_active_condition boolean,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_flags (
    flag_id text PRIMARY KEY,
    patient_id text,
    group_id text,
    encounter_id text,
    author_practitioner_id text,
    flag_status text,
    flag_code text,
    flag_system text,
    flag_display text,
    flag_text text,
    category_code text,
    category_system text,
    category_display text,
    category_text text,
    period_start timestamptz,
    period_end timestamptz,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_observations (
    observation_id text PRIMARY KEY,
    patient_id text,
    group_id text,
    location_id text,
    encounter_id text,
    performer_practitioner_id text,
    observation_status text,
    observation_code text,
    observation_system text,
    observation_display text,
    observation_text text,
    category_1_code text,
    category_1_system text,
    category_1_display text,
    category_2_code text,
    category_2_system text,
    category_2_display text,
    effective_datetime timestamptz,
    issued_datetime timestamptz,
    value_string text,
    value_boolean boolean,
    value_quantity numeric,
    value_quantity_unit text,
    value_quantity_code text,
    value_quantity_system text,
    value_codeable_concept_code text,
    value_codeable_concept_system text,
    value_codeable_concept_display text,
    value_codeable_concept_text text,
    practitioner_tag_id text,
    care_team_tag_id text,
    organization_tag_id text,
    location_tag_id text,
    app_version text,
    version_id text,
    last_updated timestamptz,
    airbyte_extracted_at timestamptz,
    dwh_updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwh.fact_observation_components (
    observation_id text,
    component_index integer,
    component_code text,
    component_system text,
    component_display text,
    component_text text,
    value_string text,
    value_boolean boolean,
    value_quantity numeric,
    value_quantity_unit text,
    value_quantity_code text,
    value_quantity_system text,
    value_codeable_concept_code text,
    value_codeable_concept_system text,
    value_codeable_concept_display text,
    value_codeable_concept_text text,
    dwh_updated_at timestamptz DEFAULT now(),
    PRIMARY KEY (observation_id, component_index)
);
